"""update payment

Revision ID: 05800bd41f51
Revises: faa93826a028
Create Date: 2025-04-25 07:28:21.480028

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '05800bd41f51'
down_revision = 'faa93826a028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('cardnumber',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_column('carddate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carddate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('cardnumber',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
