"""brand2

Revision ID: 12630ab0fc13
Revises: b709077cacf0
Create Date: 2025-04-23 06:26:07.976068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12630ab0fc13'
down_revision = 'b709077cacf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
