"""brand3

Revision ID: 1404a00f4573
Revises: bdf30a720ab7
Create Date: 2025-04-23 10:52:37.228249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1404a00f4573'
down_revision = 'bdf30a720ab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
