"""Add cascade on delete for OrderDetails

Revision ID: 151bf6114ef4
Revises: df3d0308cf1b
Create Date: 2025-04-26 09:38:17.164970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151bf6114ef4'
down_revision = 'df3d0308cf1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.drop_constraint('order_details_product_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('order_details_order_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'product', ['product_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'customer_order', ['order_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_details_order_id_fkey', 'customer_order', ['order_id'], ['id'])
        batch_op.create_foreign_key('order_details_product_id_fkey', 'product', ['product_id'], ['id'])

    # ### end Alembic commands ###
