"""update wishlist

Revision ID: 186028f8239d
Revises: 88e2241aa0de
Create Date: 2025-04-26 11:14:08.276811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186028f8239d'
down_revision = '88e2241aa0de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
