"""orderstatus2

Revision ID: 1ec366c01fed
Revises: f7153b99af16
Create Date: 2025-04-23 08:47:09.921298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec366c01fed'
down_revision = 'f7153b99af16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
