"""payments

Revision ID: 494abc1e73a3
Revises: cbeff4bd738e
Create Date: 2025-03-21 12:29:44.094541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '494abc1e73a3'
down_revision = 'cbeff4bd738e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    # ### end Alembic commands ###
