"""add product

Revision ID: 4daa1498964d
Revises: a9c7bc4bc755
Create Date: 2025-04-20 17:05:24.441264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4daa1498964d'
down_revision = 'a9c7bc4bc755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sku', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('stock', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('main_image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('customerorder_id', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
        batch_op.create_unique_constraint(None, ['sku'])
        batch_op.create_foreign_key(None, 'customer_order', ['customerorder_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.drop_column('customerorder_id')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('main_image')
        batch_op.drop_column('stock')
        batch_op.drop_column('sku')

    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
