"""update brand

Revision ID: 7496961485f4
Revises: 151bf6114ef4
Create Date: 2025-04-26 09:46:26.573320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7496961485f4'
down_revision = '151bf6114ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('description',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)

    # ### end Alembic commands ###
