"""empty message

Revision ID: 783f9068a0e5
Revises: e74fc778da5b
Create Date: 2025-04-25 14:38:09.663472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783f9068a0e5'
down_revision = 'e74fc778da5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
