"""update wishlist

Revision ID: 88e2241aa0de
Revises: f038c7b34a7d
Create Date: 2025-04-26 11:13:09.902547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88e2241aa0de'
down_revision = 'f038c7b34a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
