"""add the product

Revision ID: 9eebaa6270a4
Revises: d5e4ec836725
Create Date: 2025-04-22 19:55:48.943787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eebaa6270a4'
down_revision = 'd5e4ec836725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_image')
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=True)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.JSON(), nullable=True))
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('brand_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('customerorder_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('product_order_id_fkey', type_='foreignkey')
        batch_op.drop_column('order_id')
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('product_order_id_fkey', 'customer_order', ['order_id'], ['id'])
        batch_op.alter_column('customerorder_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('brand_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('images')

    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=True)

    op.create_table('product_image',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('is_main', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='product_image_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='product_image_pkey')
    )
    # ### end Alembic commands ###
