"""category

Revision ID: a121bc0fe9d5
Revises: 3753a5dbcaca
Create Date: 2025-03-25 10:30:08.531592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a121bc0fe9d5'
down_revision = '3753a5dbcaca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productreviews', schema=None) as batch_op:
        batch_op.drop_constraint('productreviews_product_id_fkey', type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productreviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('productreviews_product_id_fkey', 'product', ['product_id'], ['id'])

    # ### end Alembic commands ###
