"""Add status column to OrderStatus

Revision ID: a7a966221d3a
Revises: f85f55a7204d
Create Date: 2025-04-28 17:27:22.430385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a966221d3a'
down_revision = 'f85f55a7204d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
