"""product1

Revision ID: c65732ded138
Revises: 9eebaa6270a4
Create Date: 2025-04-22 20:58:09.995853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c65732ded138'
down_revision = '9eebaa6270a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('brand_name_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_brand_name'), ['name'], unique=True)
        batch_op.drop_column('logo')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_category_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('category_slug_key', type_='unique')
        batch_op.create_foreign_key(None, 'category', ['parent_category_id'], ['id'])
        batch_op.drop_column('slug')

    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('category_slug_key', ['slug'])
        batch_op.drop_column('parent_category_id')

    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_brand_name'))
        batch_op.create_unique_constraint('brand_name_key', ['name'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###
