"""update shippingAddress

Revision ID: c6abc2f437c1
Revises: 05800bd41f51
Create Date: 2025-04-25 11:50:09.119733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6abc2f437c1'
down_revision = '05800bd41f51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=True)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint('payment_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('cardnumber')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('shipping_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=140), nullable=True))
        batch_op.drop_column('shippingddress')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipping_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shippingddress', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
        batch_op.drop_column('address')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cardnumber', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('payment_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
