"""Product

Revision ID: cc6446431758
Revises: cd1482280432
Create Date: 2025-03-25 17:22:38.056604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6446431758'
down_revision = 'cd1482280432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))
        batch_op.drop_column('logo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
