"""Product

Revision ID: cd1482280432
Revises: a121bc0fe9d5
Create Date: 2025-03-25 13:00:49.825749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1482280432'
down_revision = 'a121bc0fe9d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.String(length=200), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('logo')

    # ### end Alembic commands ###
