"""add brand

Revision ID: da5fc03c4cb1
Revises: 9525777836cc
Create Date: 2025-04-20 17:04:00.124615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da5fc03c4cb1'
down_revision = '9525777836cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo', sa.String(length=500), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('description')

    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.drop_column('logo')

    # ### end Alembic commands ###
