"""remove order table

Revision ID: e4ef28cace42
Revises: a9d7e519f510
Create Date: 2025-04-02 04:10:01.121827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ef28cace42'
down_revision = 'a9d7e519f510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=True)

    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.drop_constraint('order_details_order_id_fkey', type_='foreignkey')
        batch_op.drop_column('order_id')

    with op.batch_alter_table('order_status', schema=None) as batch_op:
        batch_op.drop_constraint('order_status_order_id_fkey', type_='foreignkey')
        batch_op.drop_column('order_id')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('product_order_id_fkey', type_='foreignkey')
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('product_order_id_fkey', 'order', ['order_id'], ['id'])

    with op.batch_alter_table('order_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('order_status_order_id_fkey', 'order', ['order_id'], ['id'])

    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('order_details_order_id_fkey', 'order', ['order_id'], ['id'])

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
