"""payments

Revision ID: e664c8886700
Revises: cbeff4bd738e
Create Date: 2025-03-25 05:39:28.541537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e664c8886700'
down_revision = 'cbeff4bd738e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment', sa.String(length=140), nullable=True),
    sa.Column('logo', sa.String(length=200), nullable=True),
    sa.Column('cardnumber', sa.Integer(), nullable=True),
    sa.Column('carddate', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    # ### end Alembic commands ###
