"""Add status field to OrderStatus

Revision ID: f85f55a7204d
Revises: 378bb7121665
Create Date: 2025-04-28 17:03:29.030581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f85f55a7204d'
down_revision = '378bb7121665'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('order_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=64), nullable=False, server_default='Pending'))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('order_status', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
