"""add useraddress in User

Revision ID: faa93826a028
Revises: 6ac06f2ec990
Create Date: 2025-04-25 06:13:16.569194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa93826a028'
down_revision = '6ac06f2ec990'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=9),
               existing_nullable=True)

    with op.batch_alter_table('shipping_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shippingddress', sa.String(length=140), nullable=True))
        batch_op.drop_constraint('shipping_addresses_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('SAddress')
        batch_op.drop_column('UAddress')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('useraddress', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('useraddress')

    with op.batch_alter_table('shipping_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('UAddress', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('SAddress', sa.VARCHAR(length=140), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('shipping_addresses_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('shippingddress')

    with op.batch_alter_table('customer_order', schema=None) as batch_op:
        batch_op.alter_column('cost',
               existing_type=sa.Float(precision=9),
               type_=sa.REAL(),
               existing_nullable=True)

    # ### end Alembic commands ###
